# Generated by Django 4.2.8 on 2024-01-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=255, verbose_name=[('BreakFast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')])),
                ('name', models.CharField(max_length=65)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, verbose_name=[('Reserved', 'Reserved'), ('Canceled', 'Canceled')])),
                ('date', models.DateField()),
                ('customerName', models.CharField(max_length=100)),
                ('numberOfPeople', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfSeats', models.IntegerField(verbose_name=[(1, 'Oneseater'), (2, 'Twoseater'), (3, 'Threeseater'), (4, 'Fourseater'), (5, 'Fiveseater'), (6, 'Sixseater')])),
                ('status', models.CharField(max_length=255, verbose_name=[('Free', 'Free'), ('Reserved', 'Reserved'), ('Occupied', 'Occupied')])),
            ],
        ),
    ]
