# Generated by Django 4.2.8 on 2024-01-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_items',
            name='description',
            field=models.CharField(default='Default', max_length=255),
            preserve_default=False,
        ),
    ]
