# Generated by Django 4.2.8 on 2024-01-31 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0002_menu_items_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='date',
        ),
        migrations.AddField(
            model_name='reservations',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 14, 33, 25, 296938)),
        ),
    ]
