# Generated by Django 4.2.8 on 2024-01-31 17:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0012_alter_reservations_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='status',
        ),
        migrations.AddField(
            model_name='reservations',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rms_app.table'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 17, 50, 13, 942794)),
        ),
        migrations.AlterField(
            model_name='table',
            name='numberOfSeats',
            field=models.IntegerField(verbose_name=[(1, 'Oneseater'), (2, 'Twoseater')]),
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(max_length=255, verbose_name=[('Free', 'Free'), ('Reserved', 'Reserved')]),
        ),
    ]
