# Generated by Django 4.2.8 on 2024-01-31 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0013_remove_reservations_status_reservations_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 17, 50, 18, 778244)),
        ),
    ]
