# Generated by Django 4.2.8 on 2024-02-01 01:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0015_alter_reservations_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneSeater_Booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TwoSeater_Booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='menu_items',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='menu_items',
            name='section',
            field=models.CharField(max_length=20, verbose_name=[('BreakFast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')]),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 1, 22, 12, 163184)),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='rms_app.table'),
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(max_length=20, verbose_name=[('Free', 'Free'), ('Reserved', 'Reserved')]),
        ),
    ]
