# Generated by Django 4.2.8 on 2024-02-02 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0017_alter_reservations_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_seater_available', models.BooleanField()),
                ('two_seater_available', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='OneSeater_Booked',
        ),
        migrations.DeleteModel(
            name='TwoSeater_Booked',
        ),
        migrations.RenameField(
            model_name='reservations',
            old_name='customerName',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='reservations',
            old_name='numberOfPeople',
            new_name='number_of_people',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='status',
            new_name='table_status',
        ),
        migrations.RemoveField(
            model_name='table',
            name='numberOfSeats',
        ),
        migrations.AddField(
            model_name='table',
            name='number_of_seats',
            field=models.IntegerField(default=1, verbose_name=[(1, 'One Seater'), (2, 'Two Seater')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservations',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
