# Generated by Django 4.2.8 on 2024-02-25 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0018_booking_delete_oneseater_booked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=65)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='TimeSlots',
        ),
        migrations.RenameField(
            model_name='reservations',
            old_name='number_of_people',
            new_name='number_of_guests',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='table',
            name='number_of_seats',
        ),
        migrations.RemoveField(
            model_name='table',
            name='table_status',
        ),
        migrations.AddField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservations',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rms_app.table'),
        ),
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='reservations',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rms_app.guest'),
        ),
    ]
