# Generated by Django 4.2.8 on 2024-02-25 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0019_guest_delete_booking_delete_timeslots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 25, 22, 24, 4, 965328, tzinfo=datetime.timezone.utc)),
        ),
    ]
