# Generated by Django 4.2.8 on 2024-02-25 22:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0022_alter_reservations_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2024, 2, 25, 22, 38, 49, 254035, tzinfo=datetime.timezone.utc))),
                ('number_of_guests', models.IntegerField()),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rms_app.guest')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rms_app.table')),
            ],
        ),
        migrations.DeleteModel(
            name='Reservations',
        ),
    ]
