# Generated by Django 4.2.8 on 2024-02-25 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0023_reservation_delete_reservations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 25, 22, 38, 53, 953795, tzinfo=datetime.timezone.utc)),
        ),
    ]
