# Generated by Django 4.2.8 on 2024-03-03 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0025_alter_guest_id_alter_reservation_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 3, 13, 40, 1, 520271, tzinfo=datetime.timezone.utc)),
        ),
    ]
