# Generated by Django 4.2.8 on 2024-03-03 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0028_alter_reservation_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 3, 17, 56, 20, 108444, tzinfo=datetime.timezone.utc)),
        ),
    ]
